version: '3'
services:
    app:
      build: .
      environment:
        DB_URL: ${DB_URL}
        DEBUG: ${DEBUG}
        NODE_ENV: ${NODE_ENV}
        TZ: ${TZ}
      ports:
        - 3000:3000
      restart: unless-stopped
